### ISSUE TITLE
Return created virtual server

### ISSUE THREAD

**Issue by Cedev** [a10networks/acos-client#101]
As an acos_client user, I'd like the created or updated virtual server to be returned from `client.slb.virtual_server.create`, `client.slb.virtual_server.update`, `client.slb.service_group.create`, and `client.slb.service_group.update`
- [ ] v2.1
- [x] v3.0

**Comment by Cedev** [comment]
This seems to have been un-done in merge #113 .

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
