### ISSUE TITLE
Reopen session and retry on invalid admin session errors

### ISSUE THREAD

**Issue by Cedev** [a10networks/acos-client#104]
As an acos_client user, I'd like my commands to be retried in a new session when my admin session randomly goes away.

**Comment by Cedev** [comment]
Please don't actually do this; I'd far rather have the invalid admin session bug be fixed upstream.

**Comment by Cedev** [comment]
Retry support for invalid sessions in v3.0 is in PR #119

**Comment by mdurrant-b3** [comment]
Closed by #123
