### ISSUE TITLE
A question about the aXAPI reference of v3.0

### ISSUE THREAD

**Issue by userlocalhost** [a10networks/acos-client#158]
We use virtual appliances of ACOS v4.1.1. And they could be managed through the aXAPI v3.0 as you know.

I could get the aXAPI reference of v2.1 by following.
> ftp://srv01.marubeni-sys.com/other/network1/A10/%8E%91%97%BF/ACOS%202.7.2/references/A10_Thunder_aXAPI_Ref-v21-2014_05_16b.pdf

But I have never found the API reference of v3.0.

If that is public, could you please tell me the URL of it.

Thank you.

**Comment by userlocalhost** [comment]
I got it by a sale-engineer of A10 Networks.
 
Thank you.

**Comment by yuvaci58** [comment]
I cant access this address 
Could you help me?
ftp://srv01.marubeni-sys.com/

**Comment by userlocalhost** [comment]
I also can't access it. Its domain seems to be disabled afterwards :(
