### ISSUE TITLE
Compatibility with other Python versions

### ISSUE THREAD

**Issue by tarkatronic** [a10networks/acos-client#170]
My team and I need to be able to use this library in Python 3.6, so I've begun testing against that.

In the process, however, I found that the tests are currently only passing against 2.7; they are not even passing currently against 2.6 or pypy2. Interestingly, it appears that Travis is no longer building this project, so this was never exposed.

I have begun the process of fixing the compatibility, which will likely result in a number of pull requests in order to make them smaller and more easily consumable.

**Comment by bosatsu** [comment]
This should be resolved by https://github.com/a10networks/acos-client/pull/174
