### ISSUE TITLE
slb delete() methods do not raise NotFound exception

### ISSUE THREAD

**Issue by bosatsu** [a10networks/acos-client#185]
In both v21 and v30 of acos_client, when calling the `.delete()` method on any slb object, `slb.server.delete()` for example, if the object does not exist on the Load-Balancer, the method returns nothing, rather than raising `acos_client.errors.NotFound`, similar to the `.update()` or '.get() methods.

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
