### ISSUE TITLE
Many slb methods do not return a json response

### ISSUE THREAD

**Issue by bosatsu** [a10networks/acos-client#186]
In both v21 and v30 of acos_client, when calling the `.create()`, `.update()` or `.delete()` method on various slb objects, `slb.service.group.create()` or `slb.server.delete() ` for example, the acos_client doesn't return anything:

```
>>> r = v1.slb.server.create('test99', '1.1.1.1')
>>> type(r)
<class 'NoneType'>
```

This seems to be mostly because there are not `return` statements in the method itself:

```
    def create(self, name, ip_address, **kwargs):
        params = {
            "server": {
                "name": name,
                "host": ip_address,
                "status": kwargs.get('status', 1)
            }
        }
        self._post("slb.server.create", params, **kwargs)
```

It would be helpful, especially in the v21 client which always returns a status code of `200` for these methods to return the json back from the load-balancer.

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
