### ISSUE TITLE
v21 and v30 slb.virtual_server.create does not support vip_template

### ISSUE THREAD

**Issue by jjmanzer** [a10networks/acos-client#208]
Given a fresh A10 with V21 or V30 API support
when calling slb.virtual_server.create('foo', vip_template='ICMP-RATE-LIMIT')
then the virtual-server template should be applied like so...

```
!! slb virtual-server foo x.x.x.x /24
!!    template virtual-server ICMP-RATE-LIMIT
```

This is so API users can control their own ICMP rate limit values on vips.

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
