### ISSUE TITLE
v21 and v30 slb.virtual_server.vport.create does not support tcp_template (and presumably udp_template)

### ISSUE THREAD

**Issue by jjmanzer** [a10networks/acos-client#209]
Given an existing virtual_server on an A10 with V21 or V30 API support
when calling `slb.virtual_server.vport.create('foo', tcp_template='CONN-TIMEOUT-15S')`
or when calling `slb.virtual_server.vport.create('foo', udp_template='CONN-TIMEOUT-15S')`
then the tcp or udp templates should be applied like so...

```
!! slb virtual-server SG2NLHG558C1558-WEB-VS x.x.x.x /24
!!    port 80  tcp
!!       name foo
!!       template tcp CONN-TIMEOUT-15S
```
or
```
!! slb virtual-server SG2NLHG558C1558-WEB-VS x.x.x.x /24
!!    port 80  udp
!!       name foo
!!       template dup CONN-TIMEOUT-15S
```
This is so API users can control their own idle-timeout values on vports.

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
