### ISSUE TITLE
need way to set ha-conn-mirror in v21 and v30

### ISSUE THREAD

**Issue by jjmanzer** [a10networks/acos-client#211]
Given an existing `virtual_server` called foo on an A10 with V21 or V30 API support
When calling `slb.virtual_server.vport.create('foo', 'bar', ha_conn_mirror=1)`
Then the attribute should assigned like so...

```
!! slb virtual-server foo x.x.x.x /24
!!    port 80  tcp
!!       name bar
!!       ha-conn-mirror
```

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
