### ISSUE TITLE
'ServiceGroup' object has no attribute 'all'

### ISSUE THREAD

**Issue by ajwillo** [a10networks/acos-client#218]
Good Afternoon,

am currently unable to pull all service groups, the ServiceGroup class does have a all function in it but for some reason is not working.

this is using AXAPI_30

```
>>> c.slb.service_group.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'ServiceGroup' object has no attribute 'all'
>>>
```

c.slb.virtual_server.all() works fine

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
