### ISSUE TITLE
How to Enable the attribute of "Client IP Sticky NAT" on AXAPI_21 Version

### ISSUE THREAD

**Issue by pengweiji** [a10networks/acos-client#266]
#### Background
A10 Version: 2.7.2-P8(build: 164)
acos-client: 1.4.6
Python Version: 3.7.4

#### Promblem
When I use acos-client 1.4.6 to set my own A10Networks, the attribute of  "**Client IP Sticky NAT**" is always disable, and I can not find the site where to set it, it does not appear in the json value which I got it from the 'cl.slb.virtual_server.vport.get' method. How can I enable the  "**Client IP Sticky NAT**" to use AXAPI_21 Version?

**Comment by hthompson-a10** [comment]
Hello we've reached the EOL of support for ACOS 2.7. Please reach out to support@a10networks.com for further information.
