### ISSUE TITLE
The sample provided in the Readme does not work

### ISSUE THREAD

**Issue by lprofico** [a10networks/acos-client#49]
Maybe something changed in the API since the sample has been written.
Had to modify it to make it work:

import acos_client as acos

c = acos.Client('172.31.31.31', acos.AXAPI_21, 'admin', 'a10')
c.slb.server.create('s1', '1.1.1.1')
c.slb.server.create('s2', '1.1.1.2')
c.slb.service_group.create('pool1', c.slb.service_group.TCP,
                           c.slb.service_group.ROUND_ROBIN)
c.slb.virtual_server.create("vip1", '1.1.1.3', 1,) 
c.slb.virtual_server.vport.create("vip1", "vs1", c.slb.virtual_server.vport.HTTP, 80, "pool1") 
c.slb.hm.create("hm1", c.slb.hm.HTTP, 5, 5, 5, 'GET', '/', '19', 80)
c.slb.service_group.update('pool1', health_monitor='hm1')
c.slb.service_group.member.create("pool1", "s1", 80)
c.slb.service_group.member.create("pool1", "s2", 80)

**Comment by nickbender** [comment]
Sorry for the syntax changes. Readme is updated and should work  now. Let us know if you run into any other issues.
