### ISSUE TITLE
SSL Cert and SSL Key objects cannot be updated in v30

### ISSUE THREAD

**Issue by 0xtobit** [a10networks/acos-client#56]

**Comment by mdurrant-b3** [comment]
??? I think I fixed this but I'm not sure.  Let's test and find out.

I foresee the following issues:
- Updating existing certs with attached templates... I've tried doing this through the UI and get some funky errors back that aren't obvious "Hey you can't change this while something else is using it".  The errors should be more obvious.
- Terminated HTTPS - Updating a cert where only the cert data and expiration date have changed (one of the most common use cases) should be seamless.  
- Non-terminated HTTPS: Example: member servers A, B, and D have been updated but C has not.   This means C must not be given any new connections until it can get the updated certificate.  How much of this needs to be handled in our software?

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
