### ISSUE TITLE
axapi_http is hard-coding debug level for logs

### ISSUE THREAD

**Issue by dougwig** [a10networks/acos-client#75]

**Comment by kderynski** [comment]
I have also noticed that issue. As temporary fix hard-coded levels can be overwritten ex.

http_client.HTTPConnection.debuglevel = 0
acos.v21.axapi_http.LOG.setLevel(logging.INFO)
acos.v21.axapi_http.out_hdlr.setLevel(logging.INFO)

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
