### ISSUE TITLE
axapi_http is logging password details

### ISSUE THREAD

**Issue by dougwig** [a10networks/acos-client#76]

**Comment by mdurrant-b3** [comment]
This can be fixed in the respective `axapi_http` classes as  we can process url/headers/payloads using a single method (`strip_sensitive_data`) or similar.

**Comment by mdurrant-b3** [comment]
In 'axapi_http.py', we can redact sensitive data based on a set of regexes that match on `password=`, etc.  Doing it here allows us to have a single point of entry for logging to ensure sensitive data is ALWAYS stripped.

**Comment by mdurrant-b3** [comment]
Doing issue cleanup... AFAIK, we've redacted wherever possible.  Anything left is the result of overzealous logging in requests and would need to have the appropriate `requests` lib logging turned down in ... `neutron.conf`?

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
