### ISSUE TITLE
extended_stats in virtual_server/virtual_port

### ISSUE THREAD

**Issue by ghost** [a10networks/acos-client#89]
Support the subject.

Also no-dest-nat on virtual ports.
Also sampling-enable on virtual ports

**Comment by Cedev** [comment]
Sampling-enable was merged in in #113, no-dest-nat is a separate, completed story. Are extended_stats done and merged? If so this can be closed.

**Comment by hthompson-a10** [comment]
Issue is stale. Closing for now. Please re-open if required.
